import { DonationType } from "@/util/type";

export const getDonations = async (): Promise<DonationType[]> => {
  return [
    {
      id: 1,
      amount: 10,
      specialMessage: "very grateful for your help",
      socialURLOrBuyMeACoffee: "buymecoffee.com",
      donorId: 1,
      recipientId: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 2,
      amount: 25,
      specialMessage: "Thank you for your incredible support!",
      socialURLOrBuyMeACoffee: "patreon.com",
      donorId: 3,
      recipientId: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 3,
      amount: 50,
      specialMessage: "You're making a real difference!",
      socialURLOrBuyMeACoffee: "paypal.com",
      donorId: 4,
      recipientId: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 4,
      amount: 5,
      specialMessage: "Every little bit helps. Thank you!",
      socialURLOrBuyMeACoffee: "ko-fi.com",
      donorId: 2,
      recipientId: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 5,
      amount: 100,
      specialMessage: "Your work inspires me, thank you!",
      socialURLOrBuyMeACoffee: "buymeacoffee.com",
      donorId: 5,
      recipientId: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 6,
      amount: 15,
      specialMessage: "I believe in what you're doing, keep it up!",
      socialURLOrBuyMeACoffee: "patreon.com",
      donorId: 6,
      recipientId: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];
};
