import { UserDataType } from "@/util/type";

export const getUsersData = async (): Promise<UserDataType[]> => {
  return [
    {
      email: "user1@example.com",
      password: "hashed_password1",
      username: "user123",
      createdAt: new Date(),
      updatedAt: new Date(),
      profile: {
        name: "John Doe",
        about: "Software Developer",
        avatarImage: "https://example.com/avatar1.jpg",
        socialMediaURL: "https://twitter.com/johndoe",
        backgroundImage: "https://example.com/bg1.jpg",
        successMessage: "Thanks for your support!",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      bankCard: {
        country: "USA",
        firstName: "John",
        lastName: "Doe",
        cardNumber: "1234567812345678",
        expiryDate: new Date("2027-12-31"),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      receivedDonations: {
        amount: 50,
        specialMessage: "Keep up the great work!",
        socialURLOrBuyMeACoffee: "https://buymeacoffee.com/johndoe",
        donorId: 2,
        recipientId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    },
    {
      email: "user2@example.com",
      password: "hashed_password2",
      username: "user456",
      createdAt: new Date(),
      updatedAt: new Date(),
      profile: {
        name: "Jane Smith",
        about: "Graphic Designer",
        avatarImage: "https://example.com/avatar2.jpg",
        socialMediaURL: "https://twitter.com/janesmith",
        backgroundImage: "https://example.com/bg2.jpg",
        successMessage: "Your support means a lot!",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      bankCard: {
        country: "Canada",
        firstName: "Jane",
        lastName: "Smith",
        cardNumber: "8765432187654321",
        expiryDate: new Date("2028-06-30"),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      receivedDonations: {
        amount: 30,
        specialMessage: "You're amazing!",
        socialURLOrBuyMeACoffee: "https://buymeacoffee.com/janesmith",
        donorId: 1,
        recipientId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    },
    {
      email: "user3@example.com",
      password: "hashed_password3",
      username: "user789",
      createdAt: new Date(),
      updatedAt: new Date(),
      profile: {
        name: "Mike Johnson",
        about: "Content Creator",
        avatarImage: "https://example.com/avatar3.jpg",
        socialMediaURL: "https://twitter.com/mikejohnson",
        backgroundImage: "https://example.com/bg3.jpg",
        successMessage: "Thank you for your generosity!",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      bankCard: {
        country: "UK",
        firstName: "Mike",
        lastName: "Johnson",
        cardNumber: "1122334455667788",
        expiryDate: new Date("2029-09-30"),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      receivedDonations: {
        amount: 75,
        specialMessage: "Love your content!",
        socialURLOrBuyMeACoffee: "https://buymeacoffee.com/mikejohnson",
        donorId: 2,
        recipientId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    },
  ];
};
