import { UserType } from "@/util/type";

export const getUsers = async (): Promise<UserType[]> => {
  return [
    {
      id: 1,
      email: "test@gmail.com",
      password: "Pass1234",
      username: "testname",
      receivedDonations: 100,
      profile: "profile_testname",
      bankCard: "bank_card_testname",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 2,
      email: "john.doe@example.com",
      password: "SecurePass567",
      username: "johndoe",
      receivedDonations: 50,
      profile: "profile_john_doe",
      bankCard: "bank_card_john",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 3,
      email: "anna.schmidt@example.com",
      password: "Password123",
      username: "annaschmidt",
      receivedDonations: 200,
      profile: "profile_anna_schmidt",
      bankCard: "bank_card_anna",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 4,
      email: "lucas.dubois@example.com",
      password: "SecureP@ss890",
      username: "lucasdubois",
      receivedDonations: 75,
      profile: "profile_lucas_dubois",
      bankCard: "bank_card_lucas",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 5,
      email: "sakura.tanaka@example.com",
      password: "StrongP@ssw0rd",
      username: "sakuratanaka",
      receivedDonations: 120,
      profile: "profile_sakura_tanaka",
      bankCard: "bank_card_sakura",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 6,
      email: "arjun.sharma@example.com",
      password: "ArjunSecure123",
      username: "arjunsharma",
      receivedDonations: 150,
      profile: "profile_arjun_sharma",
      bankCard: "bank_card_arjun",
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];
};
